### ISSUE TITLE
ALB Subnets Question

### ISSUE THREAD

**Issue by pmacca** [stanb/Comformation#19]
Hi, Thanks for publishing this library - it would have been super handy when I started writing CF from hand a couple of years ago 😂.

I'm looking at converting those templates into c#, but have come up with a challenge with subnets.

I have a template where the subnets are passed as a parameter:
```
Parameters:

    ALBSubnets:
        Description: Choose which subnets the Application Load Balancer should be deployed to
        Type: List<AWS::EC2::Subnet::Id>
```

Then used to in a LoadBalancer

```
    LoadBalancer:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            Subnets: !Ref ALBSubnets
```

The input value is actually a reference to output of another stack:
```
  WebsiteAndALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://xxxx.yaml
      Parameters:
        ALBSubnets: 
          Fn::ImportValue: !Sub "${NetworkStack}-PublicSubnets"
```

Question is:
- Can I use an equivalent of ::ImportValue or something for this?
- If not, could I use an array/list of strings? I can't quite work out the syntax.
